#!/usr/bin/env bash

UNPACKED=redis-5.0.7
ARCHIVE=$UNPACKED.tar.gz
SHA256=61db74eabf6801f057fd24b590232f2f337d422280fd19486eca03be87d3a82b

check() {
    # Installs to this location, which local to the project.
    # See if the file exists.
    ls $REQD_PREFIX/bin/redis-server
}

resources() {
    local url=http://download.redis.io/releases/$ARCHIVE
    echo $url $ARCHIVE sha256 $SHA256
}

install() {
    tar -xf $ARCHIVE
    cd $UNPACKED
    PREFIX=$REQD_PREFIX make -j $REQD_J install
}

reqd_main "$@"
