#!/usr/bin/env bash

UNPACKED=redis-5.0.3
ARCHIVE=$UNPACKED.tar.gz
SHA256=e290b4ddf817b26254a74d5d564095b11f9cd20d8f165459efa53eb63cd93e02

check() {
    # Installs to this location, which local to the project.
    # See if the file exists.
    ls $REQD_PREFIX/bin/redis-server
}

resources() {
    local url=http://download.redis.io/releases/$ARCHIVE
    echo $url $ARCHIVE sha256 $SHA256
}

install() {
    tar -xf $ARCHIVE
    cd $UNPACKED
    PREFIX=$REQD_PREFIX make -j $REQD_J install
}

reqd_main "$@"
