#!/usr/bin/env bash

UNPACKED=redis-5.0.5
ARCHIVE=$UNPACKED.tar.gz
SHA256=2139009799d21d8ff94fc40b7f36ac46699b9e1254086299f8d3b223ca54a375

check() {
    # Installs to this location, which local to the project.
    # See if the file exists.
    ls $REQD_PREFIX/bin/redis-server
}

resources() {
    local url=http://download.redis.io/releases/$ARCHIVE
    echo $url $ARCHIVE sha256 $SHA256
}

install() {
    tar -xf $ARCHIVE
    cd $UNPACKED
    PREFIX=$REQD_PREFIX make -j $REQD_J install
}

reqd_main "$@"
