language: generic
os: osx
before_install:
  - which make
  - make --version; true # GNU
  - make -V MAKE_VERSION 2>/dev/null; true # BSD (not supported)
script:
  - ./test/bin/test-suite
notifications:
  email:
    on_success: never
